### ISSUE TITLE
Geometoryのデザイン崩れに関して

### ISSUE THREAD

**Issue by crane-hiromu** [totokit4/DoraPresentationTimer#17]
理想のデザインがわからんから、それを知りたい🤔
（before / after あるかなと思ったけど、gitの差分見た感じも、新しく追加した部分だから、わからんくて...）

twitter だと長くなりそうだから、こっちにやりとり残したほうが良いかなと思い！

**Comment by bannzai** [comment]
@totokit4 ちゃんと出てくるない？

<img width="756" alt="image" src="https://user-images.githubusercontent.com/10897361/200980830-6982d6b3-ac4d-4241-b487-0e3716a1e19d.png">

**Comment by bannzai** [comment]
まあ強いていうならGeometryReader部分全部いらんな。とは思った

<img width="1467" alt="image" src="https://user-images.githubusercontent.com/10897361/200980983-0ed95105-482d-4a5a-a3b8-df804220cafd.png">

**Comment by crane-hiromu** [comment]
そうなんよ、俺も動いてそうだなと思って、理想のデザインを知りたかったんよな笑

**Comment by bannzai** [comment]
ちなみに上寄せになる要因はGeometryReader { }.padding() の後ろで .border(Color.red) とかつけてみるとGeometryReader自体はサイズ決定できなる要素がないから表示できるスペースいっぱいに広がって下まで伸びるから。

<img width="1510" alt="image" src="https://user-images.githubusercontent.com/10897361/200981282-7a9940ed-e456-4bd0-b03d-089fbd128ffb.png">

**Comment by uhooi** [comment]
ワイもデバッグしてみた
上寄せでなく中央寄せにしたいと予想

**Comment by totokit4** [comment]
ありがとう〜！
762c5afd4c47591cb5b6e7b5384ea06b01711afa のコミットで直しました
